spring.application.name=pythogorean-apis

spring.datasource.url=jdbc:postgresql://localhost:5432/pythogorean?options=-c%20TimeZone%3DAsia%2FKolkata
spring.datasource.username=pythogorean
spring.datasource.password=pythogorean

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
pythogorean.vision.base-url=http://localhost:8000
pythogorean.vision.connect-timeout-ms=2000
pythogorean.vision.read-timeout-ms=10000
pythogorean.aruco.dictionary=DICT_4X4_250
pythogorean.aruco.card-size=900
